### ISSUE TITLE
Parse available loader options

### ISSUE THREAD

**Issue by evidens** [andreypopp/webpack-package-loaders-plugin#1]
It looks like you removed support for RegEx strings in the test property and don't have support for include/exclude also being some sort of pattern.

Was there a particular issue that caused you to remove that functionality?
I think it would be easier for people porting their configs over to just use the string form of the RegEx.

This library looks like it might handle what that case https://github.com/IonicaBizau/node-regex-parser

I'm willing to add the functionality but wanted to get your feedback first.

**Comment by andreypopp** [comment]
It supports glob patterns right now. I think globs are easier though I
understand that familiarity wins here. I'm open to a PR. But I think I like
to keep globs too under testGlob, excludeGlob, includeGlob keys.

**Comment by andreypopp** [comment]
There's also thing to note, now pattern only applies to files within the package and so I made glob match the part of filename relative to package root. I think regexp should also do that as there's little to no reason to match against full filename.

**Comment by revolunet** [comment]
Minimatch can handle most of patterns ? https://github.com/andreypopp/webpack-package-loaders-plugin/blob/master/src/index.js#L26

**Comment by andreypopp** [comment]
I added support for include/exclude. Don't think we should add RegExp support to be honest. Closing this. Feel free to reopen if you think there's anything actionable left.
