### ISSUE TITLE
Enable different loaders depending on `NODE_ENV`

### ISSUE THREAD

**Issue by moretti** [andreypopp/webpack-package-loaders-plugin#2]
I really like the idea behind this plugin.

I'm wondering if it would be possible to have different configurations for each environment.

For example, let's say that I have a `mainProject` which depends on `lib`.
Both of them have `babel-loader` enabled in their `package.json`:

```
"webpack": {
    "loaders": [
      {
        "test": "*.js",
        "loader": "babel-loader?stage=0"
      }
    ]
  }
```

How can I add for example `react-hot-loader` to both packages when `process.env.NODE_ENV !== 'production'`?

**Comment by andreypopp** [comment]
I think `react-hot-loader` is better to configure through an app's `webpack.config.js`.

**Comment by andreypopp** [comment]
Another idea: this could be handled by a special loader which injects other loaders depending on env var. I don't want to introduce such complexity into this plugin. Especially given that the currently described use case is better suited by `webpack.config.js` configuration. Feel free to discuss and reopen if you think there's anything actionable left.

**Comment by moretti** [comment]
Yeah, I completely understand that, it should be probably handled by another plugin.

It's just that I find this plugin really nice, but I couldn't use it in our main project because our css and js loaders have different settings depending on `process.env.NODE_ENV` :smile:

I think that browserify has the same problem when source transforms are specified in the `package.json`.

**Comment by andreypopp** [comment]
You always can write a loader which do different loaders depending on
NODE_ENV:

dev-loader?underlying=react-hot
